name: check4

on:
  pull_request:
    branches: [ master ]

jobs:
  check4:
    name: check4
    runs-on: ubuntu-latest
    steps:
      # Set up GOPATH
      - name: set up
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
        id: go
      # Check out this repository
      - name: checkout
        uses: actions/checkout@v4
      # Store cache
      - name: cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # Run golangci-lint using reviewdog
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.github_token }}
          level: warning
          golangci_lint_flags: "--config=.github/.golangci.yml"
          reporter: github-pr-review
          go_version: "1.22"
          golangci_lint_version: "v1.58.2"
      # Run test
      - name: test
        run: go test -cover ./...
